// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebAppWithDBAncona.Models;

#nullable disable

namespace MultiPageWebAppWithDBAncona.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20230906001850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiPageWebAppWithDBAncona.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "123 This Way, Des Moines, IA 51234",
                            Name = "Lisa Jefferson",
                            Note = "Met at school",
                            PhoneNumber = "515-555-1234"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "123 That Way, Des Moines, IA 55678",
                            Name = "Bill Jameson",
                            Note = "Friend of Lisa",
                            PhoneNumber = "515-555-5678"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "123 That Way, Des Moines, IA 51357",
                            Name = "Steve Stevens",
                            Note = "From math class",
                            PhoneNumber = "515-555-1357"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
